apiVersion: v1
kind: Service

metadata:
  name: fitfusion-api-service
  namespace: fitfusion

spec:
  selector:
    app: fitfusion-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: NodePort