import requests
import json

BASE_URL = "http://localhost:7071/api/tools/execute"


def call_tool(tool_name, arguments):
    """
    Sends a request to the FitFusion tool execution endpoint.

    tool_name: Name of the registered tool
    arguments: Dictionary containing tool input
    """

    payload = {
        "tool": tool_name,
        "arguments": arguments
    }

    try:
        response = requests.post(
            BASE_URL,
            json=payload,
            timeout=30
        )

        print(f"\n{'=' * 60}")
        print(f"TOOL: {tool_name}")
        print(f"STATUS: {response.status_code}")
        print(f"{'=' * 60}")

        # Try to parse the JSON response
        try:
            data = response.json()
        except ValueError:
            print("Invalid JSON response:")
            print(response.text)
            return None

        # Print formatted response
        print(json.dumps(data, indent=4))

        # Stop the pipeline if the API returned an error
        if response.status_code != 200:
            print("\nPipeline stopped because this tool returned an error.")
            return None

        return data

    except requests.exceptions.RequestException as e:
        print("\nRequest failed:")
        print(e)
        return None


# ============================================================
# STEP 1: FITNESS ANALYSIS
# ============================================================

print("\nStarting FitFusion end-to-end pipeline...\n")

analysis_response = call_tool(
    "fitness.analyze",
    {
        "name": "Vijay",
        "age": 35,
        "gender": "male",
        "weight": 72.5,
        "height": 175,
        "activity_level": "moderate",
        "goal": "fat_loss"
    }
)

if analysis_response is None:
    print("\nFitness analysis failed. Pipeline stopped.")
    exit()


# Extract the target calories generated by fitness.analyze
analysis_result = analysis_response["result"]["analysis"]

target_calories = analysis_result["target_calories"]

print("\nTarget calories extracted from analysis:")
print(target_calories)


# ============================================================
# STEP 2: FITNESS RECOMMENDATIONS
# ============================================================

recommend_response = call_tool(
    "fitness.recommend",
    {
        "goal": "fat_loss",
        "diet_preference": "vegetarian",
        "daily_calories": target_calories
    }
)

if recommend_response is None:
    print("\nFitness recommendation failed. Pipeline stopped.")
    exit()


# ============================================================
# STEP 3: WORKOUT PLAN
# ============================================================

workout_response = call_tool(
    "fitness.workout_plan",
    {
        "goal": "fat_loss",
        "experience_level": "intermediate",
        "days_per_week": 5,
        "equipment": "gym"
    }
)

if workout_response is None:
    print("\nWorkout generation failed. Pipeline stopped.")
    exit()


# ============================================================
# FINAL COMPLETE FITNESS PLAN
# ============================================================

print("\n")
print("=" * 60)
print("FITFUSION COMPLETE FITNESS PLAN")
print("=" * 60)

complete_plan = {
    "profile": analysis_response["result"]["profile"],
    "analysis": analysis_response["result"]["analysis"],
    "nutrition_recommendations": recommend_response["result"],
    "workout_plan": workout_response["result"]
}

print(json.dumps(complete_plan, indent=4))

print("\n")
print("=" * 60)
print("FITFUSION PIPELINE COMPLETED SUCCESSFULLY")
print("=" * 60)